#server port
server:
  port: 8000
  servlet:
    context-path: /manager
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
########################################################
###FREEMARKER (FreeMarkerAutoConfiguration)
########################################################
spring:
  thymeleaf:
     cache: false
     prefix: classpath:/templates/thymeleaf/
     suffix: .html
     encoding: UTF-8
     mode: HTML5
     servlet:
       content-type: text/html

  datasource:
      druid:
        db-type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lazydsr-web-template?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j2
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true

#使用开发时日志配置
logging:
  config: classpath:config/logback-spring.xml
#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.lazydsr.manager.po
